Name: Vaishnavi Dilip Paygude --- Batch: PGCP-BDA

Submission Date: 23/08/2026 ---- Instructor: Sahil Karande

In [33]:
'''Q1. Write and Read a File
Take three lines of text from the user and write them to a file notes.txt.
Then open the file and print its full contents.'''

with open("notes.txt", "w") as file:
    for i in range(3):
        line = input("Enter a line of text: ")
        file.write(line + "\n")
with open("notes.txt", "r") as file:
    print(file.read())

Enter a line of text: Hi my name is vaishnavi
Enter a line of text: i am studying PGCP-BDA
Enter a line of text: at CDAC, Kharghar, Mumbai
Hi my name is vaishnavi
i am studying PGCP-BDA
at CDAC, Kharghar, Mumbai



In [ ]:
'''Q2. Count Lines, Words, Characters
Read a text file and print how many lines, words, and characters it contains.'''

with open("notes.txt", "r") as f:
    text=f.read()

lines = text.splitlines()
words = text.split()
characters = len(text)

print("Lines:", len(lines))
print("Words:", len(words))
print("Characters:", characters)

In [65]:
from google.colab import files

uploaded = files.upload()

with open("students.csv", "r") as f:
    next(f)

    for line in f:
        row = line.strip().split(",")
        print(row)

Saving students.csv to students (6).csv
['Rahul', '20', '85']
['Priya', '21', '90']
['Amit', '19', '78']


In [54]:
'''Q4. Average Marks from CSV (Plain Python)
Read students.csv without Pandas.
Using an accumulator, compute and print the average of the marks column.'''

file = open("students.csv", "w")

file.write("Name,Age,Marks\n")
file.write("Rahul,20,85\n")
file.write("Priya,21,90\n")
file.write("Amit,19,78\n")

file.close()

total = 0
count = 0

with open("students.csv", "r") as f:
    header = f.readline()

    for line in f:
        parts = line.strip().split(",")
        marks = int(parts[2])
        total += marks
        count += 1

print("Average marks:", total / count)

Average marks: 84.33333333333333


In [63]:
'''Q5. Find the Topper (Plain Python)
Read students.csv without Pandas and print the name of the student with the highest marks.'''

highest_marks = 0
topper = ""

with open("students.csv", "r") as f:
    next(f)

    for line in f:
        parts = line.strip().split(",")
        name = parts[0]
        marks = int(parts[2])

        if marks > highest_marks:
            highest_marks = marks
            topper = name

print("Topper:", topper)

Topper: Priya


In [56]:
'''Q6. NumPy Array Statistics
Create a NumPy array of the marks values.
Print the mean, maximum, minimum, and standard deviation.'''

import numpy as np

marks = np.array([85, 90, 78])

print("Mean:", np.mean(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Standard Deviation:", np.std(marks))

Mean: 84.33333333333333
Maximum: 90
Minimum: 78
Standard Deviation: 4.9216076867444665


In [40]:
'''Q7. NumPy Boolean Filter
Using the marks array, print only the marks greater than 70 using boolean indexing.'''

import numpy as np

marks = np.array([85, 90, 78, 69, 98, 56])

print(marks[marks > 70])

[85 90 78 98]


In [41]:
'''Q8. NumPy Matrix
Create a 3x3 matrix using np.arange(1, 10).reshape(3, 3).
Print its transpose and the sum along each axis (axis=0 and axis=1).'''

import numpy as np

matrix = np.arange(1, 10).reshape(3, 3)

print("Matrix:")
print(matrix)

print("Transpose:")
print(matrix.T)

print("Sum along axis=0:")
print(matrix.sum(axis=0))

print("Sum along axis=1:")
print(matrix.sum(axis=1))

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Sum along axis=0:
[12 15 18]
Sum along axis=1:
[ 6 15 24]


In [42]:
'''Q9. NumPy Vectorised Operation
Add a bonus of 5 to every mark using a single array operation (no loop).
Then print each mark as a fraction of the maximum mark.'''

import numpy as np

marks = np.array([78, 92, 55, 88, 40, 73, 95, 60])

marks = marks + 5

print(marks / marks.max())

[0.83 0.97 0.6  0.93 0.45 0.78 1.   0.65]


In [68]:
'''Q10. Load a DataFrame
Load students.csv into a Pandas DataFrame.
Print its shape, then show head(), info(), and describe().'''

from google.colab import files

uploaded = files.upload()

import pandas as pd
df = pd.read_csv(r"students_data_new.csv")

print("Shape:", df.shape)

print("\nHead:")
print(df.head())

print("\nInfo:")
print(df.info())

print("\nDescribe:")
print(df.describe())

Saving students_data_new.csv to students_data_new.csv
Shape: (10, 3)

Head:
    Name    City  Marks
0  Rahul  Mumbai     85
1  Priya    Pune     90
2   Amit  Mumbai     65
3  Sneha  Mumbai     78
4  Rohan   Delhi     88

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   City    10 non-null     object
 2   Marks   10 non-null     int64 
dtypes: int64(1), object(2)
memory usage: 372.0+ bytes
None

Describe:
          Marks
count  10.00000
mean   80.90000
std    10.48226
min    65.00000
25%    72.75000
50%    81.50000
75%    89.50000
max    95.00000


In [69]:
'''Q11. Select and Filter
From the DataFrame, print just the marks column.

Then print all rows where marks are greater than 80.'''
import pandas as pd

df = pd.read_csv("students_data_new.csv")

print("Marks column")
print(df["Marks"])

print("Rows where marks are greater than 80")
print(df[df["Marks"] > 80])

Marks column
0    85
1    90
2    65
3    78
4    88
5    72
6    92
7    69
8    75
9    95
Name: Marks, dtype: int64
Rows where marks are greater than 80
     Name    City  Marks
0   Rahul  Mumbai     85
1   Priya    Pune     90
4   Rohan   Delhi     88
6  Aditya  Mumbai     92
9  Anjali    Pune     95


In [70]:
'''Q12. Combined Condition
Print all students who are from Mumbai AND scored more than 70.
Show only their name and marks columns.'''


result = df[(df["City"] == "Mumbai") & (df["Marks"] > 70)]

print(result[["Name", "Marks"]])

     Name  Marks
0   Rahul     85
3   Sneha     78
6  Aditya     92
8   Karan     75


In [72]:
'''Q13. Value Counts
Print how many students come from each city using value_counts().
In a comment, name the Day-3 pattern this replaces.'''

print(df["City"].value_counts())


City
Mumbai    5
Pune      3
Delhi     2
Name: count, dtype: int64


In [74]:
'''Q14. GroupBy Mean
Using groupby, print the average marks for each city.'''

print(df.groupby("City")["Marks"].mean())

City
Delhi     78.500000
Mumbai    79.000000
Pune      85.666667
Name: Marks, dtype: float64


In [75]:
'''Q15. GroupBy Multiple Statistics
Using groupby and agg, print the mean, max, and count of marks for each city.'''

result = df.groupby("City")["Marks"].agg(["mean", "max", "count"])
print(result)

             mean  max  count
City                         
Delhi   78.500000   88      2
Mumbai  79.000000   92      5
Pune    85.666667   95      3


In [76]:
'''Q16. Add a Pass/Fail Column
Add a new column Add a new column 'result' that is 'Pass' if marks >= 50 else 'Fail'.
Print the updated DataFrame (hint: define a function and use .apply()).'''

def check_result(marks):
    if marks >= 50:
        return "Pass"
    else:
        return "Fail"

df["result"] = df["Marks"].apply(check_result)

print(df)

     Name    City  Marks result
0   Rahul  Mumbai     85   Pass
1   Priya    Pune     90   Pass
2    Amit  Mumbai     65   Pass
3   Sneha  Mumbai     78   Pass
4   Rohan   Delhi     88   Pass
5    Neha    Pune     72   Pass
6  Aditya  Mumbai     92   Pass
7   Pooja   Delhi     69   Pass
8   Karan  Mumbai     75   Pass
9  Anjali    Pune     95   Pass


In [77]:
'''Q17. Sort and Export
Sort the DataFrame by marks in descending order.
Export the sorted table to a new file sorted_students.csv.'''

sorted_df = df.sort_values(by="Marks", ascending=False)

sorted_df.to_csv("sorted_students.csv", index=False)

print(sorted_df)

     Name    City  Marks result
9  Anjali    Pune     95   Pass
6  Aditya  Mumbai     92   Pass
1   Priya    Pune     90   Pass
4   Rohan   Delhi     88   Pass
0   Rahul  Mumbai     85   Pass
3   Sneha  Mumbai     78   Pass
8   Karan  Mumbai     75   Pass
5    Neha    Pune     72   Pass
7   Pooja   Delhi     69   Pass
2    Amit  Mumbai     65   Pass


In [79]:
'''Q18. Correlation
Compute and print the correlation between hours_studied and marks.
In a comment, write one sentence interpreting what the number means.'''

from google.colab import files

uploaded = files.upload()

import pandas as pd
df = pd.read_csv(r"Student.csv")

correlation = df["time_study"].corr(df["Marks"])

print("Correlation:", correlation)

# A positive correlation means that students who study more hours tend to score higher marks.

Saving Student.csv to Student (3).csv
Correlation: 0.9422538903640543


In [83]:
'''Q19. First Machine Learning Model
Using scikit-learn LinearRegression, train a model with hours_studied as the feature and marks as the target.
Predict the marks for a student who studies 6 hours and for one who studies 10 hours.
Print the learned relationship (intercept and coefficient).'''

from google.colab import files

uploaded = files.upload()

import pandas as pd
from sklearn.linear_model import LinearRegression

df = pd.read_csv("Student.csv")


X = df[["time_study"]]
y = df["Marks"]

model = LinearRegression()
model.fit(X, y)

predictions = model.predict([[6], [10]])

print("Predicted marks for 6 hours:", predictions[0])
print("Predicted marks for 10 hours:", predictions[1])

print("Intercept:", model.intercept_)
print("Coefficient:", model.coef_[0])

Saving Student.csv to Student (6).csv
Predicted marks for 6 hours: 35.35636063500563
Predicted marks for 10 hours: 58.1113623200074
Intercept: 1.2238581075029629
Coefficient: 5.688750421250444


/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [84]:
'''Q20. Mini Project: End-to-End Analysis
Perform a small analysis on students.csv:
1) Load the data and show describe().
2) Print the topper&#39;s name and the overall average marks.
3) Show the average hours studied per city (groupby).
4) List all students who scored below 60.
5) Write 3 short insights (as comments) about what the data tells you.'''

from google.colab import files

uploaded = files.upload()

import pandas as pd
df = pd.read_csv("new_data.csv")

print("Descriptive Statistics:")
print(df.describe())

topper = df.loc[df["Marks"].idxmax(), "Name"]
average_marks = df["Marks"].mean()

print("\nTopper:", topper)
print("Overall Average Marks:", average_marks)

print("\nAverage Hours Studied per City:")
print(df.groupby("City")["time_study"].mean())

print("\nStudents scoring below 60:")
print(df[df["Marks"] < 60][["Name", "Marks"]])

# 5. Insights
# Insight 1: The topper has the highest marks in the dataset.
# Insight 2: Average study hours differ between cities.
# Insight 3: Students scoring below 60 may need additional academic support.

Saving new_data.csv to new_data.csv
Descriptive Statistics:
       time_study      Marks
count   15.000000  15.000000
mean     6.133333  74.800000
std      1.875278  16.631296
min      3.000000  45.000000
25%      4.750000  63.000000
50%      6.000000  78.000000
75%      7.750000  89.000000
max      9.000000  95.000000

Topper: Anjali
Overall Average Marks: 74.8

Average Hours Studied per City:
City
Delhi     5.5
Mumbai    6.0
Pune      7.0
Name: time_study, dtype: float64

Students scoring below 60:
     Name  Marks
2    Amit     55
7   Pooja     48
10  Vivek     58
14  Arjun     45
